/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oodj_car_rental_system;


import oodj_car_rental_system.ApplicationContext.ApplicationContext;
import oodj_car_rental_system.JForms.LoginPage;
import oodj_car_rental_system.ORMdeep.TextFileORM;
import oodj_car_rental_system.Repository.BookingRepository;
import oodj_car_rental_system.Repository.CarRepository;
import oodj_car_rental_system.Repository.DatabaseFactory;
import oodj_car_rental_system.Repository.UserRepository;
import oodj_car_rental_system.utils.PdfGenerator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DatabaseFactory databaseFactory = new DatabaseFactory("databases");

        TextFileORM textFileORM = databaseFactory.createDatabase();
        UserRepository userRepository = new UserRepository(textFileORM.getTableWriter(), textFileORM.getTableReader(), textFileORM.getTableRecordDeleter());
        CarRepository carRepository = new CarRepository(textFileORM.getTableWriter(), textFileORM.getTableReader(), textFileORM.getTableRecordDeleter());
        BookingRepository bookingRepository = new BookingRepository(textFileORM.getTableWriter(), textFileORM.getTableReader(), textFileORM.getTableRecordDeleter());
        ApplicationContext context = new ApplicationContext(userRepository, carRepository, bookingRepository);
        LoginPage startUp = new LoginPage();

//        PdfGenerator pdfGenerator = new PdfGenerator(textFileORM.getTableWriter(),textFileORM.getTableReader());
//        pdfGenerator.generatePdf("report.pdf");
        startUp.setContext(context);
        startUp.setVisible(true);



    }

}
