/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oodj_car_rental_system;


import oodj_car_rental_system.ApplicationContext.ApplicationContext;
import oodj_car_rental_system.Entities.User;
import oodj_car_rental_system.JForms.LoginPage;
import oodj_car_rental_system.Models.UserDAO;
import oodj_car_rental_system.ORMdeep.TableWriter;
import oodj_car_rental_system.ORMdeep.TextFileORM;
import oodj_car_rental_system.Repository.DatabaseFactory;
import oodj_car_rental_system.Repository.UserRepository;

import java.io.File;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DatabaseFactory databaseFactory = new DatabaseFactory("databases");

        TextFileORM textFileORM = databaseFactory.createDatabase();
        UserRepository userRepository = new UserRepository(textFileORM.getTableWriter(), textFileORM.getTableReader(), textFileORM.getTableRecordDeleter());
        ApplicationContext context = new ApplicationContext(userRepository);
        LoginPage startUp = new LoginPage();
        startUp.setContext(context);
        startUp.setVisible(true);



    }

}
