/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_car_rental_system.JForms;

import oodj_car_rental_system.ApplicationContext.ApplicationContext;
import oodj_car_rental_system.utils.PdfGenerator;

import javax.swing.*;
import java.io.File;

/**
 *
 * @author mark
 */
public class AdminDashboard extends javax.swing.JFrame {

	private ApplicationContext context;

	public void setContext(ApplicationContext context){
		this.context = context;
	}
	/**
	 * Creates new form AdminDashboard
	 */
	public AdminDashboard() {
		initComponents();
		this.setSize(720,480);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                manage_cars_btn = new javax.swing.JButton();
                manage_applications_btn = new javax.swing.JButton();
                back_btn = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                manage_bookings_btn = new javax.swing.JButton();
                booking_historty_btn = new javax.swing.JButton();
                generate_report_btn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                manage_cars_btn.setText("Manage Cars");
                manage_cars_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                manage_cars_btnActionPerformed(evt);
                        }
                });

                manage_applications_btn.setText("Manage New Users Applications");
                manage_applications_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                manage_applications_btnActionPerformed(evt);
                        }
                });

                back_btn.setText("back");
                back_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_btnActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
                jLabel1.setText("Admin Dashboard");

                manage_bookings_btn.setText("Manage Bookings");
                manage_bookings_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                manage_bookings_btnActionPerformed(evt);
                        }
                });

                booking_historty_btn.setText("Customer Booking History");
                booking_historty_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                booking_historty_btnActionPerformed(evt);
                        }
                });

                generate_report_btn.setText("Generate Report");
                generate_report_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                generate_report_btnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                                .addComponent(back_btn)
                                .addGap(41, 41, 41))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(manage_cars_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(manage_applications_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                                        .addComponent(manage_bookings_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(booking_historty_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generate_report_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(back_btn))
                                .addGap(39, 39, 39)
                                .addComponent(manage_applications_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manage_cars_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manage_bookings_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(booking_historty_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(generate_report_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(57, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void manage_applications_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_applications_btnActionPerformed
			NewUserApplications newUserApplications = new NewUserApplications();
			newUserApplications.setContext(this.context);
			newUserApplications.setVisible(true);
			dispose();
        }//GEN-LAST:event_manage_applications_btnActionPerformed

        private void manage_cars_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_cars_btnActionPerformed
			ManageCars manageCars = new ManageCars();
			manageCars.setContext(context);
			manageCars.setVisible(true);
			dispose();
        }//GEN-LAST:event_manage_cars_btnActionPerformed

        private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
			LoginPage loginPage = new LoginPage();
			loginPage.setContext(context);
			loginPage.setVisible(true);
			dispose();
        }//GEN-LAST:event_back_btnActionPerformed

        private void manage_bookings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_bookings_btnActionPerformed
            ManageBookings manageBookings = new ManageBookings();
            manageBookings.setContext(context);
            manageBookings.setVisible(true);
            dispose();
        }//GEN-LAST:event_manage_bookings_btnActionPerformed

        private void booking_historty_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_historty_btnActionPerformed
        CustomerList customerList = new CustomerList();
        customerList.setContext(context);
        customerList.setVisible(true);
        dispose();
        }//GEN-LAST:event_booking_historty_btnActionPerformed

        private void generate_report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_report_btnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify file to save");

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            try {
                PdfGenerator pdfGenerator = new PdfGenerator(context.getUserRepository(), context.getCarRepository(), context.getBookingRepository());
                pdfGenerator.generatePdf(fileToSave.getAbsolutePath());
            } catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null ,"Something went wrong");
            }
        }
        }//GEN-LAST:event_generate_report_btnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminDashboard().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton back_btn;
        private javax.swing.JButton booking_historty_btn;
        private javax.swing.JButton generate_report_btn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JButton manage_applications_btn;
        private javax.swing.JButton manage_bookings_btn;
        private javax.swing.JButton manage_cars_btn;
        // End of variables declaration//GEN-END:variables
}
