/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package oodj_car_rental_system.JForms;


import oodj_car_rental_system.App;
import oodj_car_rental_system.ApplicationContext.ApplicationContext;
import oodj_car_rental_system.Entities.cars.Car;
import oodj_car_rental_system.Entities.cars.CarFuel;
import oodj_car_rental_system.Entities.cars.CarType;
import oodj_car_rental_system.Entities.cars.GearBoxType;
import oodj_car_rental_system.Serializers.CarSerializer;

import javax.swing.*;

/**
 * @author mark
 */
public class EditCarDashboard extends javax.swing.JFrame {

    private ApplicationContext context;

    private Car car;

    public void setContext(ApplicationContext context) {
        this.context = context;
    }

    public void setCar(Car car){
        this.car = car;
    }

    /**
     * Creates new form CustomerDashboard
     */
    public EditCarDashboard() {
        initComponents();
        this.setSize(720, 480);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                name_tf = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                price_per_hour_tf = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                car_type_chb = new javax.swing.JComboBox<>();
                jLabel6 = new javax.swing.JLabel();
                car_fuel_chb = new javax.swing.JComboBox<>();
                jLabel7 = new javax.swing.JLabel();
                gearbox_chb = new javax.swing.JComboBox<>();
                back_btn = new javax.swing.JButton();
                jLabel8 = new javax.swing.JLabel();
                seats_sp = new javax.swing.JSpinner();
                edit_car_btn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
                jLabel1.setText("Add New Car");

                jLabel2.setText("Name");

                jLabel3.setText("Price per Hour");

                jLabel5.setText("Car Type");

                car_type_chb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sedan", "suv", "hatchback", "van" }));

                jLabel6.setText("Car Fuel");

                car_fuel_chb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "electric", "gasoline" }));

                jLabel7.setText("Gear Box Type");

                gearbox_chb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "automatic", "manual" }));

                back_btn.setText("Back");
                back_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_btnActionPerformed(evt);
                        }
                });

                jLabel8.setText("Seats");

                seats_sp.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

                edit_car_btn.setText("Edit Car");
                edit_car_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                edit_car_btnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(seats_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(price_per_hour_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(161, 161, 161)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(gearbox_chb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(car_fuel_chb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(car_type_chb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(edit_car_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(94, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(car_type_chb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(price_per_hour_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(car_fuel_chb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(gearbox_chb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(seats_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(edit_car_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        ManageCars manageCars = new ManageCars();
        manageCars.setContext(context);
        manageCars.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            if (this.car == null){
                JOptionPane.showMessageDialog(null, "Something went Wrong");
                return;
            }

            String carTypeVal =CarSerializer.serializeCarType(this.car.getCarType()).orElseThrow();
            String carFuelVal = CarSerializer.serializeCarFuel(this.car.getCarFuel()).orElseThrow();
            String gearBoxVal =  CarSerializer.serializeGearBoxType(this.car.getGearBoxType()).orElseThrow();
            this.name_tf.setText(car.getName());
            this.price_per_hour_tf.setText(String.valueOf(this.car.getPricePerHour()));
            this.car_type_chb.getModel().setSelectedItem(carTypeVal);
            this.car_fuel_chb.getModel().setSelectedItem(carFuelVal);
            this.gearbox_chb.getModel().setSelectedItem(gearBoxVal);
            this.seats_sp.setValue(this.car.getSeats());
        }//GEN-LAST:event_formWindowOpened

        private void edit_car_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_car_btnActionPerformed
        try {
            Car newCarInfo;
            newCarInfo = getCarInformation();

            newCarInfo.setId(this.car.getId());
            this.context.getCarRepository().editCar(newCarInfo);


            JOptionPane.showMessageDialog(null, "Car information changed");
            ManageCars manageCars = new ManageCars();
            manageCars.setContext(context);
            manageCars.setVisible(true);
            dispose();
        } catch (Exception e){
            e.printStackTrace();
        }

        }//GEN-LAST:event_edit_car_btnActionPerformed

    private void add_car_btnActionPerformed(java.awt.event.ActionEvent evt) {

//        try {
//            carToAdd = getCarInformation();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//            return;
//        }
//
//        try{
//            this.context.getCarRepository().addNewCar(carToAdd.getFist(), carToAdd.getSecond());
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(null, "Something Went Wrong , Please try again");
//        }
//
//        JOptionPane.showMessageDialog(null, "Car " + carToAdd.getFist().getName() + " successfully added");

        ManageCars manageCars = new ManageCars();
        manageCars.setContext(context);
        manageCars.setVisible(true);
        dispose();
    }


private Car getCarInformation() throws  Exception{
        String name = getCarName();
        float pricePerHour = getPricePerHour();
        int seats = getCarSeats();
        CarType carType = getCarType();
        CarFuel carFuel = getCarFuel();
        GearBoxType gearBoxType = getGearBoxType();

        return new Car(name, pricePerHour, carType, carFuel, seats, gearBoxType, true);
    }

    private  String getCarName() throws Exception{
        String name = name_tf.getText();
        if (name.equals("")){
            throw new Exception("Name field is required");
        }
        return  name;
    }
    private int getCarSeats() throws Exception{
        int seats;
        try {

            seats = (int) seats_sp.getValue();
        } catch (Exception e){
            throw new Exception("Seats should be an numeric value");
        }
        if (seats <= 0){
            throw new Exception("Seats should be an more than 0");
        }

        return seats;
    }


    private GearBoxType getGearBoxType() throws Exception{
       if (gearbox_chb.getSelectedItem() == null) {
           throw new Exception("Invalid Car Fuel Type");
       }
       String gearBoxVal = gearbox_chb.getSelectedItem().toString();
       return CarSerializer.deserializeGearBox(gearBoxVal).orElseThrow();
    }

    private CarFuel getCarFuel() throws  Exception{
       if (car_fuel_chb.getSelectedItem() == null){
           throw new Exception("Invalid Car Fuel Type");
       }
       String carFuelVal = car_fuel_chb.getSelectedItem().toString();
       return CarSerializer.deserializeCarFuel(carFuelVal).orElseThrow();
    }

    private CarType getCarType() throws Exception{
        if (car_type_chb.getSelectedItem() == null){
           throw new Exception("Invalid Car Type");
        }
        String carTypeVal = car_type_chb.getSelectedItem().toString();
        return CarSerializer.deserializeCarType(carTypeVal).orElseThrow();

    }
    private float getPricePerHour() throws Exception{
        float price_per_hour = 0;
        try{
            price_per_hour = Float.valueOf(price_per_hour_tf.getText());
        } catch (Exception e){
            throw new Exception("Invalid Price Value");
        }

        if (price_per_hour <= 0){
            throw new Exception("Price should be more than 0");
        }

        return price_per_hour;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCarDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCarDashboard().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton back_btn;
        private javax.swing.JComboBox<String> car_fuel_chb;
        private javax.swing.JComboBox<String> car_type_chb;
        private javax.swing.JButton edit_car_btn;
        private javax.swing.JComboBox<String> gearbox_chb;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JTextField name_tf;
        private javax.swing.JTextField price_per_hour_tf;
        private javax.swing.JSpinner seats_sp;
        // End of variables declaration//GEN-END:variables
}
