/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_car_rental_system.JForms;

import oodj_car_rental_system.App;
import oodj_car_rental_system.ApplicationContext.ApplicationContext;
import oodj_car_rental_system.Entities.Bookings.Booking;
import oodj_car_rental_system.Entities.Bookings.BookingStatus;
import oodj_car_rental_system.Entities.cars.Car;
import oodj_car_rental_system.Entities.users.Customer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Optional;

/**
 *
 * @author mark
 */
public class ManageBookings extends javax.swing.JFrame {

	private ApplicationContext context;
    private ArrayList<Booking> pendingBookings;

    private DefaultTableModel table;
	public void setContext(ApplicationContext context){
		this.context = context;
	}
	/**
	 *
	 * Creates new form CustomerDashboard
	 */
	public ManageBookings() {
		initComponents();
		this.setSize(720,480);
        this.table = (DefaultTableModel) jTable1.getModel();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                reject_btn = new javax.swing.JButton();
                accpet_btn = new javax.swing.JButton();
                back_btn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
                jLabel2.setText("Manage Bookings");

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "username", "car", "time", "status"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(jTable1);

                reject_btn.setText("Reject");
                reject_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                reject_btnActionPerformed(evt);
                        }
                });

                accpet_btn.setText("Accept");
                accpet_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                accpet_btnActionPerformed(evt);
                        }
                });

                back_btn.setText("Back");
                back_btn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_btnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(reject_btn)
                                                .addGap(18, 18, 18)
                                                .addComponent(accpet_btn))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(back_btn))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(32, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(back_btn))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(reject_btn)
                                        .addComponent(accpet_btn))
                                .addGap(20, 20, 20))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            Optional<ArrayList<Booking>> optionalBookings =  this.context.getBookingRepository().getAllPendingBookings();
            if (optionalBookings.isEmpty()){
                JOptionPane.showMessageDialog(null, "No pending bookings");
                return;
            }
            this.pendingBookings = optionalBookings.get();
            fillTheTable();
        }//GEN-LAST:event_formWindowOpened

        private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        AdminDashboard adminDashboard = new AdminDashboard();
        adminDashboard.setContext(context);
        adminDashboard.setVisible(true);
        dispose();
        }//GEN-LAST:event_back_btnActionPerformed

        private void reject_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject_btnActionPerformed
        Booking booking;
            try {
                booking = getSelectedBooking().orElseThrow();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong");
                return;
            }

            if (!this.context.getBookingRepository().setBookingStatus(booking, BookingStatus.REJECTED)){
                JOptionPane.showMessageDialog(null, "Something went wrong");
                return;
            }

            JOptionPane.showMessageDialog(null, "Booking rejected");

            AdminDashboard adminDashboard = new AdminDashboard();
            adminDashboard.setContext(context);
            adminDashboard.setVisible(true);
            dispose();
        }//GEN-LAST:event_reject_btnActionPerformed

        private void accpet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accpet_btnActionPerformed
        Booking booking;
            try {
                booking = getSelectedBooking().orElseThrow();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong");
                return;
            }

            if (!this.context.getBookingRepository().setBookingStatus(booking, BookingStatus.APPROVED)){
                JOptionPane.showMessageDialog(null, "Something went wrong");
                return;
            }

            JOptionPane.showMessageDialog(null, "Booking approved");

            AdminDashboard adminDashboard = new AdminDashboard();
            adminDashboard.setContext(context);
            adminDashboard.setVisible(true);
            dispose();
        }//GEN-LAST:event_accpet_btnActionPerformed

    private  Optional<Booking> getSelectedBooking(){
        int index = jTable1.getSelectedRow();
        if  (index == -1){
            return Optional.empty();
        }
        return Optional.of(this.pendingBookings.get(index));
    }

    private void fillTheTable(){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        for (Booking booking: this.pendingBookings){
            Customer customer;
            Car car;
            try{
                customer = this.context.getUserRepository().getCustomerByUserId(booking.getRelatedToUser()).orElseThrow();
                car = this.context.getCarRepository().getCarById(booking.getRelatedToCar()).orElseThrow();
                System.out.println("hello");
            } catch (Exception e){
                continue;
            }
            this.table.insertRow(this.table.getRowCount(), new Object[]{
                    customer.getUsername(), car.getName(), booking.getInitiationDate().format(formatter), booking.getStatus()
            });
        }

    }

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ManageBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ManageBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ManageBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ManageBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ManageBookings().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton accpet_btn;
        private javax.swing.JButton back_btn;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JButton reject_btn;
        // End of variables declaration//GEN-END:variables
}
